import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '@autospace/ui/src/app/globals.css';
import { ApolloProvider } from '@autospace/network/src/config/apollo';
import { Header } from '@autospace/ui/src/components/organisms/Header';
import { MenuItem } from '@autospace/utils/types';
import { Container } from '@autospace/ui/src/components/atoms/Container';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Autospace',
  description: 'Generated by create next app',
};

const MENUITEMS: MenuItem[] = [
  { label: 'Search', href: '/search' },
  { label: 'Bookings', href: '/bookings' },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ApolloProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Header menuItems={MENUITEMS} />
          <Container>{children}</Container>
        </body>
      </ApolloProvider>
    </html>
  );
}
