import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '@autospace/ui/src/app/globals.css';
import { MenuItem } from '@autospace/utils/types';
import { ApolloProvider } from '@autospace/network/src/config/apollo';
import { ToastContainer } from '@autospace/ui/src/components/molecules/Toast';
import { Container } from '@autospace/ui/src/components/atoms/Container';
import { Header } from '@autospace/ui/src/components/organisms/Header';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Autospace | Valet',
  description: 'Generated by create next app',
};

const MENUITEMS: MenuItem[] = [{ label: 'My Trips', href: '/my-trips' }];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-25`}
      >
        <ApolloProvider>
          <Header type="valet" menuItems={MENUITEMS} />
          <Container>{children}</Container>
        </ApolloProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
