import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '@autospace/ui/src/app/globals.css';
import { MenuItem } from '@autospace/utils/types';
import { ApolloProvider } from '@autospace/network/src/config/apollo';
import { ToastContainer } from '@autospace/ui/src/components/molecules/Toast';
import { Container } from '@autospace/ui/src/components/atoms/Container';
import { Header } from '@autospace/ui/src/components/organisms/Header';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Autospace | Manager',
  description: 'Generated by create next app',
};

const MENUITEMS: MenuItem[] = [
  { label: 'New Garage', href: '/new-garage' },
  { label: 'Valets', href: '/valets' },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-25`}
      >
        <ApolloProvider>
          <Header type="manager" menuItems={MENUITEMS} />
          <Container>{children}</Container>
        </ApolloProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
